parameters:
    zikula_dizkus_module.security.class: Zikula\DizkusModule\Security\Permission
    zikula_dizkus_module.event_listener.class: Zikula\DizkusModule\Listener\EventListener
    zikula_dizkus_module.blocks_helper.class: Zikula\DizkusModule\Helper\BlocksHelper

services:
    zikula_dizkus_module.security:
        class: %zikula_dizkus_module.security.class%
        tags:
            - { name: zikula.dizkus.security }
        arguments: [@request_stack, @doctrine.orm.default_entity_manager, @translator.default, @zikula_permissions_module.api.permission, @zikula_extensions_module.api.variable]
        
    zikula_dizkus_module.event_listener:
        class: %zikula_dizkus_module.event_listener.class%
        tags:
            - { name: kernel.event_subscriber }
        arguments: [@request_stack, @doctrine.orm.default_entity_manager, @router]

    zikula_dizkus_module.blocks_helper:
        class: %zikula_dizkus_module.blocks_helper.class%
        tags:
            - { name: zikula.dizkus.blocks_helper }
        arguments: [@request_stack, @doctrine.orm.default_entity_manager, @router, @zikula_users_module.current_user, @zikula_extensions_module.api.variable, @zikula_dizkus_module.security, @translator.default]