parameters:
    # Common
    zikula_dizkus_module.security.class: Zikula\DizkusModule\Security\Permission
    zikula_dizkus_module.twig.extension.class: Zikula\DizkusModule\Twig\TwigExtension
    zikula_dizkus_module.links.class: Zikula\DizkusModule\Container\LinkContainer
    # Listeners 
    zikula_dizkus_module.module_listener.class: Zikula\DizkusModule\Listener\ModuleListener
    zikula_dizkus_module.user_listener.class: Zikula\DizkusModule\Listener\UserListener
    zikula_dizkus_module.spam_listener.class: Zikula\DizkusModule\Listener\SpamListener
    zikula_dizkus_module.forum_subscription_listener.class: Zikula\DizkusModule\Listener\ForumSubscriptionListener
    zikula_dizkus_module.topic_subscription_listener.class: Zikula\DizkusModule\Listener\TopicSubscriptionListener
    zikula_dizkus_module.post_edited_notify_poster_listener.class: Zikula\DizkusModule\Listener\PostEditedNotifyPosterListener
    zikula_dizkus_module.post_bad_notify_moderator_listener.class: Zikula\DizkusModule\Listener\PostBadNotifyModeratorListener
    zikula_dizkus_module.post_deleted_notify_poster_listener.class: Zikula\DizkusModule\Listener\PostDeletedNotifyPosterListener
    zikula_dizkus_module.post_moved_notify_poster_listener.class: Zikula\DizkusModule\Listener\PostMovedNotifyPosterListener
    zikula_dizkus_module.forum_sync_listener.class: Zikula\DizkusModule\Listener\ForumSyncListener
    zikula_dizkus_module.topic_sync_listener.class: Zikula\DizkusModule\Listener\TopicSyncListener
    zikula_dizkus_module.user_sync_listener.class: Zikula\DizkusModule\Listener\UserSyncListener
    zikula_dizkus_module.sync_listener.class: Zikula\DizkusModule\Listener\SyncListener
    # Forms
    zikula_dizkus_module.forum_create.class: Zikula\DizkusModule\Form\Type\Forum\CreateForumType
    zikula_dizkus_module.forum_modify.class: Zikula\DizkusModule\Form\Type\Forum\ModifyForumType
    zikula_dizkus_module.forum_select.class: Zikula\DizkusModule\Form\Type\Forum\ForumSelectType
    # Helpers
    zikula_dizkus_module.moderators_helper.class: Zikula\DizkusModule\Helper\ModeratorsHelper
    zikula_dizkus_module.favorites_helper.class: Zikula\DizkusModule\Helper\FavoritesHelper
    zikula_dizkus_module.count_helper.class: Zikula\DizkusModule\Helper\CountHelper
    zikula_dizkus_module.synchronization_helper.class: Zikula\DizkusModule\Helper\SynchronizationHelper
    zikula_dizkus_module.rank_helper.class: Zikula\DizkusModule\Helper\RankHelper
    zikula_dizkus_module.search_helper.class: Zikula\DizkusModule\Helper\SearchHelper
    # Import    
    zikula_dizkus_module.import_helper.class: Zikula\DizkusModule\Helper\ImportHelper
    zikula_dizkus_module.import.database.class: Zikula\DizkusModule\ImportHandler\Database_ImportHandler
    zikula_dizkus_module.import.upgrade_3.class: Zikula\DizkusModule\ImportHandler\Upgrade_3_ImportHandler
    # Managers
    zikula_dizkus_module.forum_user_manager.class: Zikula\DizkusModule\Manager\ForumUserManager
    zikula_dizkus_module.forum_manager.class: Zikula\DizkusModule\Manager\ForumManager
    zikula_dizkus_module.topic_manager.class: Zikula\DizkusModule\Manager\TopicManager
    zikula_dizkus_module.post_manager.class: Zikula\DizkusModule\Manager\PostManager
    zikula_dizkus_module.settings_manager.class: Zikula\DizkusModule\Manager\SettingsManager
    # Hooks
    
services:
    
# Common

    zikula_dizkus_module.security:
        class: %zikula_dizkus_module.security.class%
        tags:
            - { name: zikula.dizkus.security }
        arguments: 
            - "@request_stack"
            - "@doctrine.orm.default_entity_manager"
            - "@translator.default"
            - "@zikula_permissions_module.api.permission"
            - "@zikula_extensions_module.api.variable"
        
    zikula_dizkus_module.twig.extension:
        class: %zikula_dizkus_module.twig.extension.class%
        tags:
            - { name: twig.extension }        
        arguments:
            - "@service_container"
        
    zikula_dizkus_module.link_container:
        class: %zikula_dizkus_module.links.class%
        lazy: true
        tags:
            - { name: zikula.link_container }
        arguments:
            - "@translator.default"
            - "@router"
            - "@zikula_permissions_module.api.permission"
            - "@zikula_extensions_module.api.variable"
            - "@zikula_users_module.current_user"
        
# Event listeners        
        
    zikula_dizkus_module.module_listener:
        class: %zikula_dizkus_module.module_listener.class%
        tags:
            - { name: kernel.event_subscriber }
        arguments:
            - "@request_stack"
            - "@doctrine.orm.default_entity_manager"
            - "@router"
            - "@hook_dispatcher.storage"
            - "@translator.default"
            - "@service_container"

    zikula_dizkus_module.user_listener:
        class: %zikula_dizkus_module.user_listener.class%
        tags:
            - { name: kernel.event_subscriber }
        arguments:
            - "@doctrine.orm.default_entity_manager"

    zikula_dizkus_module.spam_listener:
        class: %zikula_dizkus_module.spam_listener.class%
        tags:
            - { name: kernel.event_subscriber }
        arguments:
          - "@zikula_extensions_module.api.variable"
          - "@translator.default"
          - "@router"
          
    zikula_dizkus_module.forum_subscription_listener:
        class: %zikula_dizkus_module.forum_subscription_listener.class%
        tags:
            - { name: kernel.event_subscriber }
        arguments:
          - "@translator.default"
          - "@twig"
          - "@zikula_extensions_module.api.variable"
          - "@zikula_mailer_module.api.mailer"
          - "@router"        
  
    zikula_dizkus_module.topic_subscription_listener:
        class: %zikula_dizkus_module.topic_subscription_listener.class%
        tags:
            - { name: kernel.event_subscriber }
        arguments:
          - "@translator.default"
          - "@twig"
          - "@zikula_extensions_module.api.variable"
          - "@zikula_mailer_module.api.mailer"
          - "@router"
      
    zikula_dizkus_module.post_edited_notify_poster_listener:
        class: %zikula_dizkus_module.post_edited_notify_poster_listener.class%
        tags:
            - { name: kernel.event_subscriber }
        arguments:
          - "@translator.default"
          - "@twig"
          - "@zikula_extensions_module.api.variable"
          - "@zikula_mailer_module.api.mailer"
          - "@router"
      
    zikula_dizkus_module.post_bad_notify_moderator_listener:
        class: %zikula_dizkus_module.post_bad_notify_moderator_listener.class%
        tags:
            - { name: kernel.event_subscriber }
        arguments:
          - "@translator.default"
          - "@twig"
          - "@zikula_extensions_module.api.variable"
          - "@zikula_mailer_module.api.mailer"
          - "@router"
          
    zikula_dizkus_module.post_moved_notify_poster_listener:
        class: %zikula_dizkus_module.post_moved_notify_poster_listener.class%
        tags:
            - { name: kernel.event_subscriber }
        arguments:
          - "@translator.default"
          - "@twig"
          - "@zikula_extensions_module.api.variable"
          - "@zikula_mailer_module.api.mailer"
          - "@router"
          
    zikula_dizkus_module.post_deleted_notify_poster_listener:
        class: %zikula_dizkus_module.post_deleted_notify_poster_listener.class%
        tags:
            - { name: kernel.event_subscriber }
        arguments:
          - "@translator.default"
          - "@twig"
          - "@zikula_extensions_module.api.variable"
          - "@zikula_mailer_module.api.mailer"
          - "@router"
          
#    zikula_dizkus_module.forum_sync_listener:
#        class: %zikula_dizkus_module.forum_sync_listener.class%
#        tags:
#            - { name: kernel.event_subscriber }
#        arguments:
#          - "@doctrine.orm.default_entity_manager"
#          
#    zikula_dizkus_module.topic_sync_listener:
#        class: %zikula_dizkus_module.topic_sync_listener.class%
#        tags:
#            - { name: kernel.event_subscriber }
#        arguments:
#          - "@doctrine.orm.default_entity_manager"
#          
#    zikula_dizkus_module.user_sync_listener:
#        class: %zikula_dizkus_module.user_sync_listener.class%
#        tags:
#            - { name: kernel.event_subscriber }
#        arguments:
#          - "@doctrine.orm.default_entity_manager"
          
    zikula_dizkus_module.sync_listener:
        class: %zikula_dizkus_module.sync_listener.class%
        tags:
            - { name: doctrine.event_listener, event: prePersist }
            - { name: doctrine.event_listener, event: preUpdate }
            - { name: doctrine.event_listener, event: postPersist }
            - { name: doctrine.event_listener, event: postUpdate }
            - { name: doctrine.event_listener, event: postRemove } 
#            - { name: doctrine.event_listener, event: preFlush }            
#            - { name: doctrine.event_listener, event: onFlush }
#        arguments: looks like we do not need much args here
#          - "@zikula_extensions_module.api.variable"
#          - "@doctrine.orm.default_entity_manager" 

# Forms
    zikula_dizkus_module.form.type.forum_create:
        class: %zikula_dizkus_module.forum_create.class%
        tags:
            - { name: form.type, alias: zikula_dizkus_module_forum_create }
        arguments:
            - "@doctrine.orm.default_entity_manager"
            - "@zikula_dizkus_module.forum_user_manager"
            
    zikula_dizkus_module.form.type.forum_modify:
        class: %zikula_dizkus_module.forum_modify.class%
        tags:
            - { name: form.type, alias: zikula_dizkus_module_forum_modify }
        arguments:
            - "@doctrine.orm.default_entity_manager"
            - "@zikula_dizkus_module.forum_user_manager"
            
    zikula_dizkus_module.form.type.forum_select:
        class: %zikula_dizkus_module.forum_select.class%
        tags:
            - { name: form.type, alias: zikula_dizkus_module_forum_select_type }
        arguments:
            - "@zikula_dizkus_module.forum_manager"
            
            
    zikula_dizkus_module.form.type.forum_select:
        class: %zikula_dizkus_module.forum_select.class%
        tags:
            - { name: form.type, alias: zikula_dizkus_module_forum_select_type }
        arguments:
            - "@zikula_dizkus_module.forum_manager"
            
            
# Helpers

    zikula_dizkus_module.count_helper:
        class: %zikula_dizkus_module.count_helper.class%
        tags:
            - { name: zikula.dizkus.count_helper }
        arguments:
            - "@request_stack"
            - "@doctrine.orm.default_entity_manager"
            - "@zikula_users_module.current_user"
        
    zikula_dizkus_module.synchronization_helper:
        class: %zikula_dizkus_module.synchronization_helper.class%
        tags:
            - { name: zikula.dizkus.synchronization_helper }
        arguments:
            - "@doctrine.orm.default_entity_manager"
            - "@zikula_dizkus_module.count_helper"
         
    zikula_dizkus_module.rank_helper:
        class: %zikula_dizkus_module.rank_helper.class%
        tags:
            - { name: zikula.dizkus.rank_helper }
        arguments:
            - "@doctrine.orm.default_entity_manager"
            - "@zikula_dizkus_module.security"
            - "@zikula_extensions_module.api.variable"
            
    zikula_dizkus_module.helper.search_helper:
        class: %zikula_dizkus_module.search_helper.class%
        arguments:
          - '@zikula_permissions_module.api.permission'
          - '@session'
          - "@translator"
          - "@zikula_extensions_module.api.variable"
          - "@zikula_dizkus_module.forum_manager"
        tags:
            - { name: zikula.searchable_module, bundleName: ZikulaDizkusModule }
# Import 

    zikula_dizkus_module.import_helper:
        class: %zikula_dizkus_module.import_helper.class%
        tags:
            - { name: zikula.dizkus.import_helper }
        arguments:
            - "@request_stack"
            - "@doctrine.orm.default_entity_manager"
            - "@zikula_extensions_module.api.variable"
            
    zikula_dizkus_module.import.abstract_service:
        abstract: true
        arguments:
            - "@translator"
            - "@form.factory"
            - "@doctrine.orm.entity_manager"
            - "@templating"

    zikula_dizkus_module.import.upgrade_3:
        parent: zikula_dizkus_module.import.abstract_service
        class: %zikula_dizkus_module.import.upgrade_3.class%
        tags:
            - { name: 'zikula_dizkus_module.import' }       
        
# Managers

    zikula_dizkus_module.forum_user_manager:
        class: %zikula_dizkus_module.forum_user_manager.class%
        shared: false
        tags:
            - { name: zikula.dizkus.forum_user_manager }
        arguments:
            - "@translator.default"
            - "@router"
            - "@request_stack"
            - "@doctrine.orm.default_entity_manager"
            - "@zikula_users_module.current_user"
            - "@zikula_dizkus_module.security"
            - "@zikula_extensions_module.api.variable"
            - "@zikula_dizkus_module.rank_helper"

    zikula_dizkus_module.forum_manager:
        class: %zikula_dizkus_module.forum_manager.class%
        shared: false
        tags:
            - { name: zikula.dizkus.forum_manager }
        arguments:
            - "@translator.default"
            - "@router"
            - "@request_stack"
            - "@doctrine.orm.default_entity_manager"
            - "@zikula_users_module.current_user"
            - "@zikula_dizkus_module.security"
            - "@zikula_extensions_module.api.variable"
            - "@zikula_permissions_module.api.permission"
            - "@zikula_dizkus_module.forum_user_manager"

    zikula_dizkus_module.topic_manager:
        class: %zikula_dizkus_module.topic_manager.class%
        shared: false
        tags:
            - { name: zikula.dizkus.topic_manager }
        arguments: 
            - "@translator.default"
            - "@router"
            - "@request_stack"
            - "@doctrine.orm.default_entity_manager"
            - "@zikula_users_module.current_user"
            - "@zikula_dizkus_module.security"
            - "@zikula_extensions_module.api.variable"
            - "@zikula_dizkus_module.forum_user_manager"
            - "@zikula_dizkus_module.forum_manager"
            - "@zikula_dizkus_module.synchronization_helper"        
        
    zikula_dizkus_module.post_manager:
        class: %zikula_dizkus_module.post_manager.class%
        shared: false
        tags:
            - { name: zikula.dizkus.post_manager }
        arguments: 
            - "@translator.default"
            - "@router"
            - "@request_stack"
            - "@doctrine.orm.default_entity_manager"
            - "@zikula_users_module.current_user"
            - "@zikula_dizkus_module.security"
            - "@zikula_extensions_module.api.variable"
            - "@zikula_dizkus_module.forum_user_manager"
            - "@zikula_dizkus_module.forum_manager"
            - "@zikula_dizkus_module.topic_manager"
            - "@zikula_dizkus_module.synchronization_helper"

    zikula_dizkus_module.settings_manager:
        class: %zikula_dizkus_module.settings_manager.class%
        shared: false
        tags:
            - { name: zikula.dizkus.settings_manager }
        arguments: 
            - "@translator.default"
            - "@doctrine.orm.default_entity_manager"
            - "@zikula_extensions_module.api.variable"
            - "@zikula_hook_bundle.collector.hook_collector"
            - "@zikula_extensions_module.api.capability"

    zikula_dizkus_module.hook_subscriber.post_text_ui_hooks_subscriber:
        class: Zikula\DizkusModule\Hooks\PostTextSubBundle
        arguments:
          - "@translator.default"
        tags:
            - { name: zikula.hook_subscriber, areaName: "subscriber.dizkus.ui_hooks.post_text" }
            
    zikula_dizkus_module.hook_subscriber.post_ui_hooks_subscriber:
        class: Zikula\DizkusModule\Hooks\PostSubBundle
        arguments:
          - "@translator.default"
        tags:
            - { name: zikula.hook_subscriber, areaName: "subscriber.dizkus.ui_hooks.post" }
            
    zikula_dizkus_module.hook_subscriber.topic_ui_hooks_subscriber:
        class: Zikula\DizkusModule\Hooks\TopicSubBundle
        arguments:
          - "@translator.default"
        tags:
            - { name: zikula.hook_subscriber, areaName: "subscriber.dizkus.ui_hooks.topic" }
            
    zikula_dizkus_module.hook_subscriber.forum_ui_hooks_subscriber:
        class: Zikula\DizkusModule\Hooks\ForumSubBundle
        arguments:
          - "@translator.default"
        tags:
            - { name: zikula.hook_subscriber, areaName: "subscriber.dizkus.ui_hooks.forum" }            
            
    zikula_dizkus_module.hook_subscriber.post_filter_hooks_subscriber:
        class: Zikula\DizkusModule\Hooks\PostFilterSubBundle
        arguments:
          - "@translator.default"
        tags:
            - { name: zikula.hook_subscriber, areaName: "subscriber.dizkus.filter_hooks.post" }   
            
    zikula_dizkus_module.hook_provider.topic_ui_hooks_provider:
        class: Zikula\DizkusModule\Hooks\TopicProBundle
        arguments:
            - "@kernel"
            - "@translator.default"
            - "@router"
            - "@request_stack"
            - "@templating"
            - "@zikula_extensions_module.api.variable"
            - "@zikula_permissions_module.api.permission"
            - "@zikula_dizkus_module.forum_user_manager"
            - "@zikula_dizkus_module.forum_manager"
            - "@zikula_dizkus_module.topic_manager"
            - "@zikula_dizkus_module.post_manager"
        tags:
            - { name: zikula.hook_provider, areaName: "provider.dizkus.ui_hooks.topic" }

    zikula_dizkus_module.hook_provider.bbcode_ui_hooks_provider:
        class: Zikula\DizkusModule\Hooks\BBCodeProBundle
        arguments:
            - "@translator.default"
            - "@router"
            - "@request_stack"
            - "@templating"
            - "@zikula_extensions_module.api.variable"
        tags:
            - { name: zikula.hook_provider, areaName: "provider.dizkus.ui_hooks.bbcode" }

    zikula_dizkus_module.hook_provider.bbcode_filter_hooks_provider:
        class: Zikula\DizkusModule\Hooks\BBFilterProBundle
        arguments:
          - "@translator.default"
          - "@zikula_extensions_module.api.variable"
        tags:
            - { name: zikula.hook_provider, areaName: "provider.dizkus.filter_hooks.bbcode" }
